apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  labels:
    app.kubernetes.io/instance: virtualization
  name: win10-rootdisk1-hnur5
  namespace: default
spec:
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 60Gi
    storageClassName: pmo-local
    volumeMode: Filesystem
  source:
    blank: {}
